[package]
name = "day-6"
version = "0.1.0"
authors = ["Christopher Serr <cryze92@gmail.com>"]

[features]
save = ["image", "rand"]

[dependencies]
image = { version = "*", optional = true }
rand = { version = "*", optional = true }
